server:
  port: ${PORT:8082}
spring:
  application:
    name: catalog-service
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/catalog}
  threads:
    virtual:
      enabled: true
app:
  internal-key: ${INTERNAL_API_KEY:internal-secret}