server:
  port: ${PORT:8084}
spring:
  application:
    name: inventory-service
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/inventory}
  data:
    mongodb:
      auto-index-creation: true
  threads:
    virtual:
      enabled: true
app:
  internal-key: ${INTERNAL_API_KEY:internal-secret}